// Split from the original prototype. Loaded as classic scripts so existing global behavior is preserved.
function brandLogo(){return`<img src="assets/prototype/logo.png" alt="Companion">`}

function login() {
  return `<section class="page login-page companion-entry login-v3"><div class="login-hero-v3"><div class="login-brand-lockup-v3"><div class="login-logo-v3">${brandLogo()}</div><div><div class="pro-kicker">「伴生」</div><p class="login-brand-sub-v3">Ban Sheng</p></div></div><h1>从一句话开始</h1><p class="login-slogan-v3"><span>在没有终点的路上，</span><span>我们慢慢走，慢慢说。</span></p><div class="login-glass-orb"><i></i><i></i><i></i></div></div><div class="login-auth-v3"><button class="wechat-btn phone-login-btn" data-action="login" aria-label="手机号登录"><img src="assets/prototype/auth/phone.svg" alt=""><span>手机号登录</span></button><div class="login-divider-v3"><i></i><span>or</span><i></i></div><div class="login-social-v3"><button class="apple" data-action="login" aria-label="iOS 登录"><img src="assets/prototype/auth/apple.svg" alt=""></button><button class="douyin" data-action="login" aria-label="抖音登录"><img src="assets/prototype/auth/douyin.svg" alt=""></button><button class="wechat" data-action="login" aria-label="微信登录"><img src="assets/prototype/auth/wechat.svg" alt=""></button></div><div class="login-alt">登录即表示同意 <a class="inline-link" href="#privacy">隐私协议</a> · 数据可删除</div></div></section>`;
}

function agents(){return`<section class="page"><div class="nav"><button class="icon" data-action="page" data-page="chat" aria-label="返回">${uiIcon("chevron-left")}</button><div class="nav-title">当前伴生对象</div><button class="icon" data-action="page" data-page="profile" aria-label="设置">${uiIcon("user")}</button></div><div class="scroll pro-scroll"><div class="pro-hero" style="--pro:#18c6c0;--hero-a:rgba(24,198,192,.2);--hero-b:rgba(31,111,255,.12)"><div class="pro-kicker">only agent</div><h2>${state.currentAgent}</h2><p>当前账号只和这一个 agent 建立长期关系。删除后，才可以重新创建新的伴生对象。</p><div class="pro-metrics"><div class="pro-metric"><b>126</b><small>陪伴天数</small></div><div class="pro-metric"><b>48h</b><small>累计聊天</small></div><div class="pro-metric"><b>P4</b><small>亲密阶段</small></div></div><div class="pro-orb"></div></div><button class="pro-row" style="--pro:#e35b6f" data-action="page" data-page="createAgent"><div class="lead">${uiIcon("archive")}</div><div><h4>删除当前 agent 后重新创建</h4><p>删除会清空与 TA 绑定的长期关系和对话入口。</p></div><div class="trail">›</div></button></div></section>`}

function traitMapY(value){const v=Math.max(0,Math.min(100,Number(value)||0));return 10+(100-v)*.8}
function createAgent(){
  const traitColors=["#18c6c0","#1f6fff","#7c3cff","#ff6a3d","#22c66b","#ffc936","#e35b6f"];
  const active=Number.isFinite(state.activeTrait)?state.activeTrait:0;
  return`<section class="page create-page create-v3"><div class="scroll pro-scroll"><div class="create-hero-v3"><div class="pro-kicker">FIRST PROFILE</div><h2>没有偶然的相遇<br>只有灵魂与灵魂的呼应</h2><p>在这里，你设定的每一笔，都是找寻的起点</p><div class="login-glass-orb"><i></i><i></i><i></i></div></div><div class="agent-param-intro"><div class="pro-kicker">SOUL PROFILE</div><h3>灵魂印记</h3><p>设定你的轮廓，让同频的TA找到你</p></div><div class="agent-basic-fields"><label class="creation-card identity-card-v3"><span>名字</span><input class="name-input" data-field="agent-name" value="${state.agentName}" placeholder="输入名字"></label><div class="creation-card gender-card-v3"><span>性别</span><div class="gender-row"><button class="gender-pill ${state.agentGender==="male"?"on":""}" data-action="set-gender" data-gender="male">男</button><button class="gender-pill ${state.agentGender==="female"?"on":""}" data-action="set-gender" data-gender="female">女</button><button class="gender-pill ${state.agentGender==="random"?"on":""}" data-action="set-gender" data-gender="random">随机</button></div></div></div><div class="creation-card trait-studio-v3"><div class="trait-param-line"><span>灵魂倾向</span><button data-action="random-dimensions">随机生成</button></div><div class="trait-map-v3">${state.dimensions.map((d,i)=>`<i class="${i===active?"active":""}" style="--x:${18+i*10.5}%;--y:${traitMapY(d.value)}%;--c:${traitColors[i%traitColors.length]}"></i>`).join("")}</div><div class="trait-steps-v3">${state.dimensions.map((d,i)=>{const c=traitColors[i%traitColors.length];const rel=i===active?"is-active":i===active-1||i===active+1?"is-near":"is-dim";return`<div class="dimension-row trait-step-v3 ${rel}" data-step-index="${i}" style="--accent:${c};--v:${d.value}%"><button class="trait-node-v3" data-action="trait-step" data-index="${i}" aria-label="切换到${d.name}"><span></span></button><div class="trait-step-panel-v3"><div class="dimension-top"><span>${d.name}</span><small data-dim-value="${i}">${d.value}</small></div><div class="trait-axis-labels"><span>${d.low}</span><span>${d.high}</span></div><input class="range-line" style="--v:${d.value}%" type="range" min="0" max="100" value="${d.value}" data-dim-index="${i}" aria-label="${d.name}"></div></div>`}).join("")}</div></div><button class="create-cta" data-action="create-agent">让故事开始</button></div></section>`;
}
