// Split from the original prototype. Loaded as classic scripts so existing global behavior is preserved.
function chatPage(){return`<section class="page chat-page ${state.keyboard?"keyboard-open":""} ${state.emoji?"emoji-open":""} ${state.more?"more-open":""} ${state.drawer?"drawer-open":""}"><div class="chat-head"><button class="avatar image-avatar" data-action="page" data-page="profile">${agentPortrait()}</button><div class="chat-name"><b>${state.currentAgent}</b><small>互动中 · 文字 / 表情 / 功能卡片</small></div><button class="head-btn" data-action="drawer" aria-label="功能">${uiIcon("menu")}</button></div><div class="chat-scroll">${state.messages.map(messageHTML).join("")}</div><div class="composer"><div class="composer-field"><div class="input" data-action="open-keyboard">${state.keyboard?"我想找点事做，不想一直陷在坏心情里。":state.emoji?"选择一个表情…":state.more?"选择一个功能…":"发消息…"}</div><button class="input-voice" data-action="voice" aria-label="语音">${uiIcon("mic")}</button><button class="input-emoji" data-action="emoji-toggle" aria-label="表情">${uiIcon("smile")}</button></div><button class="round composer-more ${state.more?"on":""}" data-action="more-toggle" aria-label="更多功能">${uiIcon("plus")}</button></div></section>`}

function keyboardPanel(){const rows=[["Q","W","E","R","T","Y","U","I","O","P"],["A","S","D","F","G","H","J","K","L"],["⇧","Z","X","C","V","B","N","M","⌫"]];return`<div class="keyboard"><div class="keyboard-bar"><span>我想找点事做，不想一直陷在坏心情里。</span><button data-action="keyboard-close">完成</button></div>${rows.map((r,ri)=>`<div class="key-row">${r.map(k=>`<button class="key ${ri===2&&(k==="⇧"||k==="⌫")?"wide":""}" data-action="keyboard-key">${k}</button>`).join("")}</div>`).join("")}<div class="key-row"><button class="key wide" data-action="keyboard-key">123</button><button class="key wide" data-action="voice">${uiIcon("mic")}</button><button class="key space" data-action="keyboard-key">空格</button><button class="key send" data-action="keyboard-send">发送</button></div></div>`}

function emojiPanel(){const emojis=["😊","😂","🥹","🤍","🙌","🌧️","☀️","🎧","🍿","🎮","📚","🍰","🧋","🌙","✨","🫶","😌","😵‍💫","😭","👍","👀"];return`<div class="emoji-panel"><div class="emoji-head"><b>常用表情</b><button data-action="emoji-close">关闭</button></div><div class="emoji-grid">${emojis.map(e=>`<button class="emoji" data-action="emoji-pick" data-emoji="${e}">${e}</button>`).join("")}</div></div>`}

function chatMoreIcon(name){
  const icons={
    photo:`<svg class="more-svg service-svg" viewBox="0 0 36 36"><rect class="tile" x="2" y="2" width="32" height="32" rx="10"/><path class="symbol" d="M9 12.4h18v12.8H9z"/><circle class="tile-accent" cx="25.2" cy="11.4" r="3.4"/><circle class="cut" cx="14.2" cy="16.2" r="2.1"/><path class="tile-line" d="m10.8 24 5.7-5.7 3.6 3.7 2-2 4.2 4"/></svg>`,
    redpacket:`<svg class="more-svg service-svg" viewBox="0 0 36 36"><rect class="tile" x="2" y="2" width="32" height="32" rx="10"/><path class="symbol" d="M10 8.8h16v19.4H10z"/><path class="tile-line" d="M10 14.5c4.2 3.3 11.8 3.3 16 0M18 15.4v8.2M14.6 19.4h6.8"/><circle class="tile-accent" cx="26" cy="10" r="3"/></svg>`,
    call:`<svg class="more-svg service-svg" viewBox="0 0 36 36"><rect class="tile" x="2" y="2" width="32" height="32" rx="10"/><path class="symbol" d="M10.2 20.2c4.2 4.6 9.4 6.4 14.8 5.4l2.1-4.1-4.5-2.3-2.2 2c-2.4-.8-4.3-2.5-5.6-5l1.9-2.2-2.5-4.3-4.1 2.2c-.9 3.1-.8 5.9.1 8.3Z"/><path class="tile-line" d="M23.4 10.7c1.9.6 3.4 2 4 4M22.6 14.4c.9.3 1.6 1 1.9 1.9"/><circle class="tile-accent" cx="26.5" cy="23.5" r="2.8"/></svg>`,
    gift:`<svg class="more-svg service-svg" viewBox="0 0 36 36"><rect class="tile" x="2" y="2" width="32" height="32" rx="10"/><path class="symbol" d="M9 16h18v11H9z"/><path class="symbol" d="M8 12h20v5H8z"/><path class="tile-line" d="M18 12v15M10.5 16h15"/><path class="tile-line" d="M18 11c-3.2 0-5.1-1.1-5.1-2.6 0-1.2 1-2 2.2-2 1.5 0 2.5 1.4 2.9 4.6Zm0 0c3.2 0 5.1-1.1 5.1-2.6 0-1.2-1-2-2.2-2-1.5 0-2.5 1.4-2.9 4.6Z"/><circle class="tile-accent" cx="27" cy="12" r="3"/></svg>`
  };
  return icons[name]||"";
}

function chatMorePanel(){const tools=[["photo","图片","#1f6fff","#35c9ff"],["redpacket","红包","#ff4d5f","#ffbe3d"],["call","连麦","#18c6c0","#22c66b"],["gift","礼物","#7c3cff","#ff6aef"]];return`<div class="chat-more-panel" aria-label="更多功能">${tools.map(t=>`<button class="chat-tool-btn" style="--icon-ink:${t[2]};--icon-accent:${t[3]}" data-action="chat-tool" data-tool="${t[0]}"><span>${chatMoreIcon(t[0])}</span><b>${t[1]}</b></button>`).join("")}</div>`}

function messageHTML(m){if(m.from==="card")return`<div class="msg"><div class="mini-av image-avatar">${agentPortrait()}</div><button class="card-msg" data-action="open-card" data-kind="${m.kind}"><div class="tag">Companion Card</div><h4>${m.title}</h4><p>${m.desc}</p><div class="foot"><span>${m.foot}</span><span>打开 ›</span></div></button></div>`;if(m.from==="me")return`<div class="msg user"><div class="bubble">${m.text}</div><div class="mini-av image-avatar">${userPortrait()}</div></div>`;return`<div class="msg"><div class="mini-av image-avatar">${agentPortrait()}</div><div class="bubble">${m.text}</div></div>`}

function drawer(){const main=sideItems.filter(i=>i[0]!=="shop");const shop=sideItems.find(i=>i[0]==="shop");const button=(i,extra="")=>`<button class="drawer-btn ${extra}" style="--icon-soft:${i[2]};--icon-ink:${i[3]};--icon-accent:${i[4]}" aria-label="${i[1]}" data-action="page" data-page="${i[0]}">${sideIcon(i[0])}</button>`;return`<button class="scrim drawer-scrim" data-action="close"></button><div class="drawer-shell"><aside class="drawer" aria-label="快捷功能"><div class="drawer-stack">${main.map(i=>button(i)).join("")}</div></aside>${shop?`<aside class="drawer-shop-panel" aria-label="积分商城">${button(shop,"drawer-shop-btn")}</aside>`:""}</div>`}
