// Split from the original prototype. Loaded as classic scripts so existing global behavior is preserved.
function chatPage(){return`<section class="page chat-page ${state.keyboard?"keyboard-open":""} ${state.emoji?"emoji-open":""}"><div class="chat-head"><button class="avatar image-avatar" data-action="page" data-page="profile">${agentPortrait()}</button><div class="chat-name"><b>${state.currentAgent}</b><small>互动中 · 文字 / 表情 / 功能卡片</small></div><button class="head-btn" data-action="drawer" aria-label="功能">${uiIcon("menu")}</button></div><div class="chat-scroll">${state.messages.map(messageHTML).join("")}</div><div class="composer"><div class="composer-field"><div class="input" data-action="open-keyboard">${state.keyboard?"我想找点事做，不想一直陷在坏心情里。":state.emoji?"选择一个表情…":"发消息…"}</div><button class="input-voice" data-action="voice" aria-label="语音">${uiIcon("mic")}</button></div><button class="round" data-action="emoji-toggle" aria-label="表情">${uiIcon("smile")}</button></div></section>`}

function keyboardPanel(){const rows=[["Q","W","E","R","T","Y","U","I","O","P"],["A","S","D","F","G","H","J","K","L"],["⇧","Z","X","C","V","B","N","M","⌫"]];return`<div class="keyboard"><div class="keyboard-bar"><span>我想找点事做，不想一直陷在坏心情里。</span><button data-action="keyboard-close">完成</button></div>${rows.map((r,ri)=>`<div class="key-row">${r.map(k=>`<button class="key ${ri===2&&(k==="⇧"||k==="⌫")?"wide":""}" data-action="keyboard-key">${k}</button>`).join("")}</div>`).join("")}<div class="key-row"><button class="key wide" data-action="keyboard-key">123</button><button class="key wide" data-action="voice">${uiIcon("mic")}</button><button class="key space" data-action="keyboard-key">空格</button><button class="key send" data-action="keyboard-send">发送</button></div></div>`}

function emojiPanel(){const emojis=["😊","😂","🥹","🤍","🙌","🌧️","☀️","🎧","🍿","🎮","📚","🍰","🧋","🌙","✨","🫶","😌","😵‍💫","😭","👍","👀"];return`<div class="emoji-panel"><div class="emoji-head"><b>常用表情</b><button data-action="emoji-close">关闭</button></div><div class="emoji-grid">${emojis.map(e=>`<button class="emoji" data-action="emoji-pick" data-emoji="${e}">${e}</button>`).join("")}</div></div>`}

function messageHTML(m){if(m.from==="card")return`<div class="msg"><div class="mini-av image-avatar">${agentPortrait()}</div><button class="card-msg" data-action="open-card" data-kind="${m.kind}"><div class="tag">Companion Card</div><h4>${m.title}</h4><p>${m.desc}</p><div class="foot"><span>${m.foot}</span><span>打开 ›</span></div></button></div>`;if(m.from==="me")return`<div class="msg user"><div class="bubble">${m.text}</div><div class="mini-av image-avatar">${userPortrait()}</div></div>`;return`<div class="msg"><div class="mini-av image-avatar">${agentPortrait()}</div><div class="bubble">${m.text}</div></div>`}

function drawer(){return`<button class="scrim" data-action="close"></button><aside class="drawer">${sideItems.map(i=>`<button class="drawer-btn" style="--icon-soft:${i[2]};--icon-ink:${i[3]};--icon-accent:${i[4]}" aria-label="${i[1]}" data-action="page" data-page="${i[0]}">${sideIcon(i[0])}</button>`).join("")}</aside>`}
