// Split from the original prototype. Loaded as classic scripts so existing global behavior is preserved.
function movie(){const i=state.movieIndex%movieCatalog.length;const m=movieCatalog[i];const barrage=[...movieBarrage,...movieBarrage];return`<section class="page cinema-page-v6"><div class="scroll cinema-scroll-v6"><div class="cinema-actions-v6"><button class="cinema-back-v6" data-action="page" data-page="online" aria-label="返回">${uiIcon("chevron-left")}</button><button class="cinema-share-v6" data-action="share" data-kind="movie">发聊天</button></div><div class="cinema-intro-v6"><div class="pro-kicker">cinema player</div><h2>今晚的共同影厅</h2><p>今晚先看这部。想吐槽就发一句，不想说话也可以安静把这一幕看完。</p></div><div class="movie-player-v6"><div class="movie-screen-v6 ${state.movieControls?"controls-on":""}" style="--movie-poster:url('${m.poster}')" data-action="movie-toggle"><div class="movie-poster-float-v6"></div><div class="movie-topline-v6"><span>${m.title}</span><span>${m.state}</span></div><div class="movie-caption-v6"><b>正在播放 · ${m.title}</b><span>${m.subtitle}</span></div><div class="movie-inline-controls-v6"><button class="movie-play-v6" data-action="share" data-kind="movie" aria-label="播放">${uiIcon("play")}</button><div class="movie-progress-v6"><span><b>${m.time}</b><b>${m.duration}</b></span><div class="movie-bar"><i></i></div></div><div class="movie-badge-v6">${m.barrage}</div></div></div><div class="movie-rail-wrap-v6"><button class="movie-arrow-v6 prev" data-action="movie-slide" data-dir="-1" aria-label="上一部">${uiIcon("chevron-left")}</button><div class="movie-rail-v6">${movieCatalog.map((x,idx)=>`<button class="movie-poster-v6 ${idx===i?"on":""}" style="--movie-poster:url('${x.poster}')" data-action="movie-pick" data-index="${idx}" aria-label="${x.title}"><span>${x.title}</span></button>`).join("")}</div><button class="movie-arrow-v6 next" data-action="movie-slide" data-dir="1" aria-label="下一部">${uiIcon("chevron-left")}</button></div></div><div class="barrage-panel-v6"><div class="barrage-head-v6"><b>正在播放弹幕</b><span>${m.title}</span></div><div class="barrage-list-v6"><div class="barrage-track-v6">${barrage.map(x=>`<div class="barrage-row-v6"><i></i><p>${x[1]}</p><time>${x[0]}</time></div>`).join("")}</div></div></div></div></section>`}

function scrollMovieRail(keepTop){
  requestAnimationFrame(()=>{
    const page=document.querySelector(".cinema-scroll-v6");
    const top=Number.isFinite(keepTop)?keepTop:page?.scrollTop;
    const rail=document.querySelector(".movie-rail-v6");
    const active=document.querySelector(".movie-rail-v6 .on");
    if(rail&&active)rail.scrollTo({left:active.offsetLeft-rail.clientWidth/2+active.clientWidth/2,behavior:"smooth"});
    if(page&&Number.isFinite(top))page.scrollTop=top;
  });
}
