// Split from the original prototype. Loaded as classic scripts so existing global behavior is preserved.
function weather(){return`<section class="page">${nav("天气","weather")}<div class="scroll pro-scroll"><div class="pro-hero" style="--pro:#1f8fff;--hero-a:rgba(31,143,255,.22);--hero-b:rgba(255,201,54,.14)"><div class="pro-kicker">weather card</div><h2>24° 多云，傍晚适合短途散步</h2><p>小芜所在地 · 杭州。全天 19° - 27°，风力 2 级。</p><div class="pro-metrics"><div class="pro-metric"><b>42</b><small>AQI 优</small></div><div class="pro-metric"><b>62%</b><small>湿度</small></div><div class="pro-metric"><b>2级</b><small>东南风</small></div></div><div class="pro-orb"></div></div><div class="pro-line-chart"><svg viewBox="0 0 260 64" fill="none"><path d="M4 45 C38 35 56 18 92 24 C132 31 142 11 178 18 C208 23 226 33 256 21" stroke="#1f8fff" stroke-width="3" stroke-linecap="round"/><path d="M4 48 C42 52 75 44 102 50 C145 59 178 43 256 48" stroke="#22c66b" stroke-width="2" stroke-dasharray="5 6" stroke-linecap="round"/></svg></div><div class="pro-list"><button class="pro-row" style="--pro:#1f8fff" data-action="share" data-kind="weather"><div class="lead">18</div><div><h4>18:00 降温</h4><p>出门建议薄外套，小芜会在傍晚前提醒。</p></div><div class="trail">22°</div></button></div></div></section>`}

function capsule(){return`<section class="page">${nav("时间胶囊","capsule")}<div class="scroll pro-scroll"><div class="pro-hero" style="--pro:#7c3cff;--hero-a:rgba(124,60,255,.2);--hero-b:rgba(31,111,255,.12)"><div class="pro-kicker">future capsule</div><h2>把今天的话，交给未来某一天打开</h2><p>按开启时间管理所有封存内容，草稿可随时继续编辑。</p><div class="pro-actions"><button class="pro-pill primary" data-action="modal" data-modal="capsule">写新胶囊</button><button class="pro-pill">草稿 2</button></div><div class="pro-orb"></div></div><div class="section-title">2026 年 6 月开启</div><div class="pro-list">${["给考完试的自己","夏天开始前","毕业前夜"].map((x,i)=>`<button class="pro-row" style="--pro:#7c3cff" data-action="share" data-kind="capsule"><div class="lead">${i+1}</div><div><h4>${x}</h4><p>${["希望那天你已经睡了很长的一觉。","记得买一束便宜但漂亮的花。","给未来保留一点不确定的勇气。"][i]}</p></div><div class="trail">06/${["01","18","29"][i]}</div></button>`).join("")}</div></div></section>`}

function capsuleModal(){return`<button class="scrim" data-action="close-modal"></button><div class="sheet-note"><h3 style="margin-bottom:10px">写胶囊</h3><textarea>未来的我，如果今天又觉得不够好，请先去喝水、洗澡，然后再判断。</textarea><div class="btn-row"><button class="btn" data-action="close-modal">存草稿</button><button class="btn primary" data-action="save-capsule">封存</button></div></div>`}

function legacy(){return`<section class="page">${nav("遗言","legacy")}<div class="scroll pro-scroll"><div class="pro-hero" style="--pro:#151820;--hero-a:rgba(21,24,32,.18);--hero-b:rgba(124,60,255,.1)"><div class="pro-kicker">private note</div><h2>最后想说的话，只在必要时被看见</h2><p>内容以情感记录为主，触发前会要求紧急联系人确认。</p><div class="pro-metrics"><div class="pro-metric"><b>45</b><small>触发天数</small></div><div class="pro-metric"><b>2</b><small>联系人</small></div><div class="pro-metric"><b>本机</b><small>加密</small></div></div><div class="pro-orb"></div></div><div class="pro-list"><button class="pro-row" style="--pro:#151820" data-action="share" data-kind="legacy"><div class="lead">文</div><div><h4>遗言内容</h4><p>“我一直记得你做的番茄炒蛋。”</p></div><div class="trail">已保存</div></button><button class="pro-row" style="--pro:#151820"><div class="lead">联</div><div><h4>紧急联系人</h4><p>妈妈 · 138****0927；陈知远 · 186****3145</p></div><div class="trail">2 人</div></button></div></div></section>`}

function achieve(){const badges=[["初次相遇","第一段完整对话","#1f6fff","01"],["七日不断","连续陪伴一周","#22c66b","07"],["深夜树洞","被认真接住过","#7c3cff","夜"],["未来胶囊","写给未来的话","#ff6a3d","封"],["共同听歌","共享一首歌","#18c6c0","听"],["长期陪伴","关系进入 P4","#ffc936","P4"]];return`<section class="page">${nav("成就","achieve")}<div class="scroll pro-scroll"><div class="pro-hero" style="--pro:#ffc936;--hero-a:rgba(255,201,54,.24);--hero-b:rgba(124,60,255,.13)"><div class="pro-kicker">achievement</div><h2>把关系里发生过的事，变成可回看的里程碑</h2><p>成就不是任务压力，而是你们长期陪伴慢慢留下的证据。</p><div class="pro-metrics"><div class="pro-metric"><b>18</b><small>已解锁</small></div><div class="pro-metric"><b>金</b><small>最高等级</small></div><div class="pro-metric"><b>3</b><small>本周新增</small></div></div><div class="pro-orb"></div></div><div class="pro-mini-grid">${badges.map(x=>`<button class="pro-card" style="--pro:${x[2]}" data-action="share" data-kind="achieve"><div class="pro-card-icon">${x[3]}</div><h3>${x[0]}</h3><p>${x[1]}</p><footer><span>已获得</span><span>›</span></footer></button>`).join("")}</div></div></section>`}

function checkin(){const week=["一","二","三","四","五","六","日"];return`<section class="page">${nav("打卡提醒","checkin")}<div class="scroll pro-scroll"><div class="pro-hero habit-hero"><div class="pro-kicker">habit rhythm</div><h2>提醒不是催促，是有人陪你把一天收住</h2><p>小芜会按你的状态选择语音、消息或轻提醒，不把打卡做成压力。</p><div class="habit-week">${week.map((d,i)=>`<span class="habit-day ${[1,2,4,5].includes(i)?"on":""}">${d}</span>`).join("")}</div></div><div class="section-title">今天的时间线</div><div class="habit-line"><button class="habit-item" data-time="08:10" data-action="share" data-kind="checkin"><h4>轻声叫起床</h4><p>先给 5 分钟缓冲，再确认今天第一件事。</p></button><button class="habit-item" data-time="20:30" data-action="share" data-kind="checkin"><h4>工作冲刺 25 分钟</h4><p>番茄钟期间只保留必要提醒，结束后建议休息。</p></button><button class="habit-item" data-time="22:40" data-action="share" data-kind="checkin"><h4>睡前收尾</h4><p>把未完成的事放到明天，不让它继续占据睡眠。</p></button></div></div></section>`}

function shop(){const items=[["极简气泡","320 积分","▱","#1f6fff"],["蓝雾背景","520 积分","◌","#18c6c0"],["银线头像框","680 积分","◎","#7c3cff"],["补签卡 x1","120 积分","✓","#22c66b"]];return`<section class="page">${nav("积分商城","shop")}<div class="scroll pro-scroll"><div class="pro-hero" style="--pro:#ff6a3d;--hero-a:rgba(255,106,61,.18);--hero-b:rgba(255,201,54,.17)"><div class="pro-kicker">point shop</div><h2>2,816 积分</h2><p>只保留能让对话更有质感的小物件：气泡、背景、头像框和补签卡。</p><div class="pro-actions"><button class="pro-pill primary">气泡</button><button class="pro-pill">背景</button><button class="pro-pill">头像框</button></div><div class="pro-orb"></div></div><div class="pro-grid">${items.map(x=>`<button class="pro-card" style="--pro:${x[3]}" data-action="share" data-kind="shop"><div class="pro-card-icon">${x[2]}</div><h3>${x[0]}</h3><p>${x[1]} · 可立即兑换并应用到聊天。</p><footer><span>兑换</span><span>›</span></footer></button>`).join("")}</div></div></section>`}
